### ISSUE TITLE
additional DMI documentation

### ISSUE THREAD

**Issue by ZeWaka** [20kdc/byond-data-docs#1]
Hi, whoever is interested should probably add the information lummox's writeup on the old DMI format http://www.byond.com/forum/post/189170#comment1077677

re: https://github.com/20kdc/byond-data-docs/blob/master/formats/DMI.md

**Comment by 20kdc** [comment]
Ah, thank you! I didn't know about this

**Comment by 20kdc** [comment]
A link to the documentation has been committed. I am also keeping a local backup which will be inserted in the event said link goes dead.
